services:
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    restart: always
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:443:443/udp
      - 0.0.0.0:2019:2019
    volumes:
      - caddy_data:/data
      - caddy_config:/config

      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs

      - ./etc/caddy/alextheplumber.Caddyfile:/etc/caddy/alextheplumber.Caddyfile
      - ./etc/caddy/idertator.Caddyfile:/etc/caddy/idertator.Caddyfile
      - ./etc/caddy/topgroupx.Caddyfile:/etc/caddy/topgroupx.Caddyfile
      - ./etc/caddy/xyztem.Caddyfile:/etc/caddy/xyztem.Caddyfile

    command: [ "caddy", "run", "--watch", "--config", "/etc/caddy/Caddyfile" ]
    networks:
      - xyztem

networks:
  xyztem:
    external: true

volumes:
  caddy_data:
  caddy_config:
